# Generated by Django 5.2.9 on 2025-12-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewerprofile',
            name='status',
            field=models.CharField(choices=[('AWAITING_INFORMATION', 'Awaiting Information'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='AWAITING_INFORMATION', max_length=25),
        ),
    ]
